services:
  securechain-depex:
    container_name: securechain-depex
    build:
      context: ..
      dockerfile: dev/Dockerfile
    volumes:
      - ../app:/app
    env_file:
      - ../.env
    ports:
      - '8002:8000'
    networks:
      - securechain
    depends_on:
      - redis

  securechain-auth:
    container_name: securechain-auth
    image: ghcr.io/securechaindev/securechain-auth:latest
    env_file:
      - ../.env
    ports:
      - '8001:8000'
    networks:
      - securechain

  redis:
    container_name: securechain-redis
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - securechain
    command: redis-server --appendonly yes

networks:
  securechain:
    name: securechain
    external: true
    driver: bridge

volumes:
  redis-data:
